version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "weekly"
      ignore:
          - dependency-name: "org.springframework.boot"
            versions: ["3.x"]
      commit-message:
          prefix: "deps"
          include: "scope"
      labels:
          - "dependencies"
          - "security"
      open-pull-requests-limit: 10
      reviewers:
          - "your-github-username"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "ci"
          include: "scope"
      labels:
          - "ci-cd"
          - "dependencies"
