server:
    port: 8080
    servlet:
        session:
            timeout: 30m # 会话超时时间
            cookie:
                http-only: true # 防止XSS访问cookie
                same-site: strict # 防止CSRF

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/security_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            cachePrepStmts: true

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                use_sql_comments: false
                jdbc:
                    batch_size: 25
                    batch_versioned_data: true
        defer-datasource-initialization: true

    sql:
        init:
            mode: always
            platform: mysql
            continue-on-error: true

    springdoc:
        api-docs:
            path: /v3/api-docs
        swagger-ui:
            path: /swagger-ui.html
        packages-to-scan: com.example.security.controller

    security:
        session:
            concurrency-control:
                max-sessions: 1
                error-if-maximum-exceeded: true

jwt:
    secret: your-secret-key
    expiration: 86400000 # 24小时

logging:
    level:
        com.example.security.converter: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: TRACE
