server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/security_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        mvc:
            pathmatch:
                matching-strategy: ant_path_matcher

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true

    sql:
        init:
            mode: always
            continue-on-error: true

jwt:
    secret: your-secret-key
    expiration: 86400000 # 24小时
