name: Java CI with Maven

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 8
              uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"
                  cache: maven

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2

            - name: Build with Maven
              run: mvn -B package --file pom.xml

            - name: Run Tests
              run: mvn test

            - name: Run Security Check
              run: |
                  chmod +x ./security-check.sh
                  ./security-check.sh

            - name: Upload Test Results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: target/surefire-reports/

            - name: Upload Security Reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: security-reports
                  path: |
                      target/dependency-check-report.html
                      target/dependency-check-report.json
